export const UPDATE_TYPE = 'UPDATE_TYPE'
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT'
export const SORT_COMPONENT = 'SORT_COMPONENT'

export const INGEST_DATA = 'INGEST_DATA'

export const UPDATE_ORDER_NUMBER = 'UPDATE_ORDER_NUMBER'
export const UPDATE_ORDER_NUMBER_LOADING = 'UPDATE_ORDER_NUMBER_LOADING'
export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE'

export const HIDE_MODAL = 'HIDE_MODAL'
export const SHOW_INGREDIENT_MODAL = 'SHOW_INGREDIENT_MODAL'
export const SHOW_ORDER_MODAL = 'SHOW_ORDER_MODAL'

export const UPDATE_CART = 'UPDATE_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const UPDATE_INGREDIENTS = 'UPDATE_INGREDIENTS'
export const SORT_INGREDIENTS = 'SORT_INGREDIENTS'

export const MOVE_CARD = 'MOVE_CARD'

