export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE'

export const HIDE_MODAL = 'HIDE_MODAL'
export const SHOW_INGREDIENT_MODAL = 'SHOW_INGREDIENT_MODAL'

export const UPDATE_CART = 'UPDATE_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const MOVE_CARD = 'MOVE_CARD'

export const GET_INGREDIENTS = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'

export const SEND_ORDER = 'SEND_ORDER'
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'