export const UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE' = 'UPDATE_TOTAL_PRICE'

export const HIDE_MODAL: 'HIDE_MODAL' = 'HIDE_MODAL'
export const SHOW_INGREDIENT_MODAL: 'SHOW_INGREDIENT_MODAL' = 'SHOW_INGREDIENT_MODAL'

export const UPDATE_CART: 'UPDATE_CART' = 'UPDATE_CART'
export const REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART' = 'REMOVE_ITEM_FROM_CART'

export const MOVE_CARD: 'MOVE_CARD' = 'MOVE_CARD'

export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS'
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED'
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS'

export const SEND_ORDER: 'SEND_ORDER' = 'SEND_ORDER'
export const SEND_ORDER_FAILED: 'SEND_ORDER_FAILED' = 'SEND_ORDER_FAILED'
export const SEND_ORDER_SUCCESS: 'SEND_ORDER_SUCCESS' = 'SEND_ORDER_SUCCESS'

export const REGISTER: 'REGISTER' = 'REGISTER'
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED'
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS'

export const LOGIN: 'LOGIN' = 'LOGIN'
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED'
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS'

export const LOGOUT: 'LOGOUT' = 'LOGOUT'
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED'
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS'

export const AUTH: 'AUTH' = 'AUTH'
export const AUTH_FAILED: 'AUTH_FAILED' = 'AUTH_FAILED'
export const AUTH_SUCCESS: 'AUTH_SUCCESS' = 'AUTH_SUCCESS'

export const FORGOT_PASSWORD: 'FORGOT_PASSWORD' = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED'

export const RESET_PASSWORD: 'RESET_PASSWORD' = 'RESET_PASSWORD'
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED'

export const SET_USER_DATA: 'SET_USER_DATA' = 'SET_USER_DATA'

export const WS_CONNECTION_INIT: 'WS_CONNECTION_INIT' = 'WS_CONNECTION_INIT'
export const WS_CONNECTION_REQUEST: 'WS_CONNECTION_REQUEST' = 'WS_CONNECTION_REQUEST'
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS'
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR'
export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE'
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED'
export const WS_ON_MESSAGE: 'WS_ON_MESSAGE' = 'WS_ON_MESSAGE'
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE'

export const PROCESS_ORDERS: 'PROCESS_ORDERS' = 'PROCESS_ORDERS'
export const SET_TYPE: 'SET_TYPE' = 'SET_TYPE'

export const webSocketURL = 'wss://norma.nomoreparties.space'